blog/urls.py
from .views import *
from django.urls import path

app_name = 'blog'

urlpatterns = [
    path('', blog, name='blog'),
    path('category/<int:category_id>/', category, name='category'),
]

contact/urls.py
from django.urls import path
from .views import *

app_name = 'contact'

urlpatterns = [
    path('', contact, name='contact'),
]

core/urls.py
from .views import *
from django.urls import path

app_name = 'core'

urlpatterns = [
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('store/', store, name='store'),

]

pages/urls.py
from django.urls import path
from .views import *

app_name = 'pages'

urlpatterns = [
    path('<int:page_id>/<slug:page_slug>', page, name='page'),
]

services/urls.py
from .views import *
from django.urls import path

app_name = 'services'

urlpatterns = [
        path('', services, name='services'),
]

social/urls.py
from .views import *
from django.urls import path

urlpatterns = [

]

web_empresa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path('services/', include('services.urls', namespace='services')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('page/', include('pages.urls', namespace='page')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils.timezone import now
from django.contrib.auth.models import User

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Nombre')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')
    updated = models.DateTimeField(auto_now=True, verbose_name='Fecha de edicion')

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ['-created']

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=200, verbose_name='Título')
    content = models.TextField(verbose_name='Contenido')
    published = models.DateTimeField(verbose_name='Fecha de publicación', default=now)
    image = models.ImageField(upload_to='blog', verbose_name='Imagen', null=True, blank=True)
    author = models.ForeignKey(User, verbose_name='Author', on_delete=models.CASCADE)
    categories = models.ManyToManyField(Category, verbose_name='Categorias', related_name='get_posts')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')
    updated = models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')

    class Meta:
        verbose_name = 'Entrada'
        verbose_name_plural = 'Entradas'
        ordering = ['-created']

    def __str__(self):
        return self.title

contact/models.py
from django.db import models

# Create your models here.

core/models.py
from django.db import models

# Create your models here.

pages/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.


class Page(models.Model):
    title = models.CharField(verbose_name='Titulo', max_length=100)
    content = RichTextField(verbose_name='Contenido')
    order = models.SmallIntegerField(verbose_name='orden', default=0)
    created = models.DateTimeField(verbose_name='Fecha de creación', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='Fecha de Edicion', auto_now=True)

    class Meta:
        verbose_name = 'Pagina'
        verbose_name_plural = 'paginas'
        ordering = ['order', 'title']

    def __str__(self):
        return self.title

services/models.py
from django.db import models

# Create your models here.


class Service(models.Model):
    title = models.CharField(max_length=200, verbose_name='Título')
    subtitle = models.CharField(max_length=200, verbose_name='Subtitulo')
    content = models.TextField(verbose_name='Contenido')
    image = models.ImageField(upload_to='services', verbose_name='Imagen')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')
    updated = models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')

    class Meta:
        verbose_name = 'Servicio'
        verbose_name_plural = 'Servicios'
        ordering = ['-created']

    def __str__(self):
        return self.title

social/models.py
from django.db import models

# Create your models here.


class Link(models.Model):
    key = models.SlugField(verbose_name='Nombre clave', max_length=100, unique=True)
    name = models.CharField(verbose_name='Nombre', max_length=70)
    url = models.URLField(verbose_name='Enlace', max_length=200, null=True, blank=True)
    created = models.DateTimeField(verbose_name='Fecha de creacion', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='Fecha de edición', auto_now=True)

    class Meta:
        verbose_name = 'Enlace'
        verbose_name_plural = 'Enlaces'
        ordering = ['name']

    def __str__(self):
        return self.name

contact/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(label='Nombre', required=True)
    email = forms.EmailField(label='Email', required=True)
    content = forms.CharField(label='Mensaje', required=True, widget=forms.Textarea)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import *

# Create your views here.


def blog(request):
    posts = Post.objects.all()
    return render(request, 'blog/blog.html', {'posts': posts})


def category(request, category_id):
    category_ = get_object_or_404(Category, id=category_id)
    posts = Post.objects.filter(categories=category_)
    return render(request, 'blog/category.html', {'category': category_})

contact/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import ContactForm

# Create your views here.


def contact(request):
    contact_form = ContactForm()
    if request.method == 'POST':
        contact_form = ContactForm(data=request.POST)
        if contact_form.is_valid():
            name = request.POST.get('name', '')
            email = request.POST.get('email', '')
            content = request.POST.get('content', '')

            # suponemos que todo fue bien y redireccionamos
            return redirect(reverse('contact')+'?ok')

    return render(request, 'contact/contact.html', {'contact_form': contact_form})

core/views.py
from django.shortcuts import render, HttpResponse

# Create your views here.


def home(request):
    return render(request, 'core/home.html')


def about(request):
    return render(request, 'core/about.html')


def store(request):
    return render(request, 'core/store.html')

pages/views.py
from django.shortcuts import render, get_object_or_404
from .models import Page

# Create your views here.


def page(request, page_id, page_slug):
    page_ = get_object_or_404(Page, id=page_id)
    return render(request, 'pages/sample.html', {'page': page_})

services/views.py
from django.shortcuts import render
from .models import Service

# Create your views here.


def services(request):
    all_services = Service.objects.all()
    return render(request, 'services/services.html', {'services': all_services})

social/views.py
from django.shortcuts import render

# Create your views here.

blog/templates/blog/blog.html
{% extends 'core/layout.html' %}


{% load static %}

{% block title %}Blog{% endblock %}

{% block content %}
    {% for post in posts %}
        <section class="page-section cta">
          <div class="container">
            <div class="row">
              <div class="col-xl-9 mx-auto">
                <div class="cta-innerv text-center rounded">
                  <h2 class="section-heading mb-5">
                    <span class="section-heading-upper">{{ post.published|date:'SHORT_DATE_FORMAT'}}</span>
                    <span class="section-heading-lower">{{ post.title }}</span>
                  </h2>
                  <p class="mb-0">
                    <img class="mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="{{ post.image.url }}" alt="">
                  </p>
                  <p class="mb-0 mbt">
                    {{ post.content|linebreaks }}
                  </p>
                  <p class="mb-0 mbt">
                    <span class="section-heading-under">Publicado por <em><b>{{ post.author }}</b></em> en
                        <en>
                          {% for category in post.categories.all %}

                              <a href="{% url 'blog:category' category.id %}" class="link">{{ category.name }}</a>{% if not forloop.last %},{% endif %}
                          {% endfor %}
                        </en>
                    </span>
                  </p>
                </div>

              </div>
            </div>
          </div>
        </section>
    {% endfor %}
{% endblock %}


    

blog/templates/blog/category.html
{% extends 'core/layout.html' %}


{% load static %}

{% block title %}Blog{% endblock %}

{% block content %}
    {% for post in category.get_posts.all %}
        <section class="page-section cta">
          <div class="container">
            <div class="row">
              <div class="col-xl-9 mx-auto">
                <div class="cta-innerv text-center rounded">
                  <h2 class="section-heading mb-5">
                    <span class="section-heading-upper">{{ post.published|date:'SHORT_DATE_FORMAT'}}</span>
                    <span class="section-heading-lower">{{ post.title }}</span>
                  </h2>
                  <p class="mb-0">
                    <img class="mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="{{ post.image.url }}" alt="">
                  </p>
                  <p class="mb-0 mbt">
                    {{ post.content|linebreaks }}
                  </p>
                  <p class="mb-0 mbt">
                    <span class="section-heading-under">Publicado por <em><b>{{ post.author }}</b></em> en
                        <en>
                          {% for category in post.categories.all %}

                              <a href="{% url 'blog:category' category.id %}" class="link">{{ category.name }}</a>{% if not forloop.last %},{% endif %}
                          {% endfor %}
                        </en>
                    </span>
                  </p>
                </div>

              </div>
            </div>
          </div>
        </section>
    {% endfor %}
{% endblock %}

contact/templates/contact/contact.html
{% extends 'core/layout.html' %}


{% load static %}

{% block title %}Contacto{% endblock %}

{% block content %}
<section class="page-section about-heading">
  <div class="container">
    <img class="img-fluid rounded about-heading-img mb-3 mb-lg-0" src="{% static 'core/img/contact.jpg' %}" alt="">
    <div class="about-heading-content">
      <div class="row">
        <div class="col-xl-9 col-lg-10 mx-auto">
          <div class="bg-faded rounded p-5">
            <h2 class="section-heading mb-4">
              <span class="section-heading-upper">Envíanos tus dudas</span>
              <span class="section-heading-lower">Contacto</span>
            </h2>
            <!-- Formulario de contacto -->
              {% if 'ok' in request.GET %}
                <p>Su mensaje se ha enviado correctamente</p>
              {% endif %}
              <form action="" method="post">
                  {% csrf_token %}
                  <table>
                    {{ contact_form.as_table }}
                  </table>
                  <button type="submit">Enviar</button>
              </form>

            <!--<form>
                <div class="form-group">
                    <label>Nombre *</label>
                    <div class="input-group">
                        <input type="text" class="form-control">
                    </div>
                </div>
                <div class="form-group">
                    <label>Email *</label>
                    <div class="input-group">
                        <input type="text" class="form-control">
                    </div>
                    <ul class="errorlist">
                        <li>El email no es correcto.</li>
                    </ul>
                </div>
                <div class="form-group">
                    <label>Mensaje *</label>
                    <div class="input-group">
                        <textarea class="form-control"></textarea>
                    </div>
                </div>
                <div class="text-center">
                    <input type="submit" class="btn btn-primary btn-block py-2" value="Enviar">
                </div>
            </form>-->
            <!-- Fin formulario de contacto -->


          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

core/templates/core/about.html
{% extends 'core/layout.html' %}

{% load static %}

{% block title %}Historia{% endblock %}

{% block content %}
<section class="page-section about-heading">
  <div class="container">
    <img class="img-fluid rounded about-heading-img mb-3 mb-lg-0" src="{% static 'core/img/about.jpg' %}" alt="">
    <div class="about-heading-content">
      <div class="row">
        <div class="col-xl-9 col-lg-10 mx-auto">
          <div class="bg-faded rounded p-5">
            <h2 class="section-heading mb-4">
              <span class="section-heading-upper">Tradición familiar italiana</span>
              <span class="section-heading-lower">Nuestra historia</span>
            </h2>
            <p>Fundada en 1987 consectetur adipiscing elit. Donec leo dui, vehicula vel dapibus ac, tempus non enim. Nunc tempor vel lacus vel gravida. Nam sit amet pellentesque mi. </p>
            <p>Curabitur efficitur pellentesque tellus nec volutpat. In viverra mattis sem, facilisis condimentum mi rutrum ut. Quisque ut pellentesque dui.Nullam eu vehicula metus. Pellentesque id interdum elit. Aenean in efficitur enim.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

core/templates/core/base.html
<!DOCTYPE html>
<html lang="es">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %} | La Caffettiera</title>

    {% load static %}

    <!-- Bootstrap -->
    <link href="{% static 'core/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Fuentes -->
    <link href="{% static 'core/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">

    <!-- Estilos -->
    <link href="{% static 'core/css/business-casual.css' %}" rel="stylesheet">

  </head>

  <body>

    <h1 class="site-heading text-center text-white d-none d-lg-block">
      <span class="site-heading-upper text-primary mb-3">L'autentico caffè d'italia</span>
      <span class="site-heading-lower">La Caffettiera</span>
    </h1>

    <!-- Navegación -->
    <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
      <div class="container">
        <a class="navbar-brand text-uppercase text-expanded font-weight-bold d-lg-none" href="{% url 'home' %}">La Caffettiera</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav mx-auto">
            <li class="nav-item active px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'home' %}">Inicio</a>
            </li>
            <li class="nav-item px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'about' %}">Historia</a>
            </li>
            <li class="nav-item px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'services' %}">Servicios</a>
            </li>
            <li class="nav-item px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'store' %}">Visítanos</a>
            </li>
            <li class="nav-item px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'contact' %}">Contacto</a>
            </li>
            <li class="nav-item px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'blog' %}">Blog</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    {% block content %} {% endblock %}

    <!-- Pié de página -->
    <footer class="footer text-faded text-center py-5">
      <div class="container">
        <p class="m-0">
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	    </p>
        <p class="m-0 mbt">
        	<a href="../../../pages/templates/pages/sample.html" class="link">Política de privacidad</a> ·
        	<a href="../../../pages/templates/pages/sample.html" class="link">Aviso legal</a> ·
        	<a href="../../../pages/templates/pages/sample.html" class="link">Cookies</a>
		</p>
        <p class="m-0 mbt1">&copy; La Caffettiera 2018</p>
      </div>
	</footer>

    <!-- Bootstrap -->
    <script src="{% static 'core/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'core/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  </body>

</html>

core/templates/core/home.html
{% extends 'core/layout.html' %}


{% load static %}

{% block title %}Inicio{% endblock %}

{% block content %}

<!-- Cabecera -->
<section class="page-section clearfix">
  <div class="container">
    <div class="intro">
      <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{% static 'core/img/intro.jpg' %}" alt="">
      <div class="intro-text left-0 text-center bg-faded p-5 rounded">
        <h2 class="section-heading mb-4">
          <span class="section-heading-upper">Déjate sorprender</span>
          <span class="section-heading-lower">Te gustará</span>
        </h2>
        <p class="mb-3">Trabajamos sólo con los mejores ingredientes. Una vez lo pruebes, nuestro café será la mejor forma de empezar tu rutina diaria.
        </p>
        <div class="intro-button mx-auto">
          <a class="btn btn-primary btn-xl" href="{% url 'core:store' %}">Visítanos</a>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Mensaje -->
<section class="page-section cta">
  <div class="container">
    <div class="row">
      <div class="col-xl-9 mx-auto">
        <div class="cta-inner text-center rounded">
          <h2 class="section-heading mb-4">
            <span class="section-heading-upper">Compromiso total</span>
            <span class="section-heading-lower">Garantizado</span>
          </h2>
          <p class="mb-0">Sed pulvinar blandit elit id venenatis. Ut eget lacus neque. Nullam justo quam, efficitur nec turpis vitae, efficitur posuere ligula. Proin ut turpis orci. Aenean porta sodales lectus faucibus pellentesque. In sed felis iaculis, rhoncus felis a, maximus mi.</p>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

core/templates/core/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %} | La Caffettiera</title>

    <!-- Bootstrap -->
    <link href="{% static 'core/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Fuentes -->
    <link href="{% static 'core/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">

    <!-- Estilos -->
    <link href="{% static 'core/css/business-casual.css'%}" rel="stylesheet">

  </head>

  <body>

    <h1 class="site-heading text-center text-white d-none d-lg-block">
      <span class="site-heading-upper text-primary mb-3">L'autentico caffè d'italia</span>
      <span class="site-heading-lower">La Caffettiera</span>
    </h1>

    <!-- Navegación -->
    <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
      <div class="container">
        <a class="navbar-brand text-uppercase text-expanded font-weight-bold d-lg-none" href="{% url 'core:home' %}">La Caffettiera</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav mx-auto">
            <li class="nav-item {% if request.path == '/' %} active {% endif %} px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'core:home' %}">Inicio</a>
            </li>
            <li class="nav-item {% if request.path == '/about/' %} active {% endif %} px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'core:about' %}">Historia</a>
            </li>
            <li class="nav-item {% if request.path == '/services/' %} active {% endif %}  px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'services:services' %}">Servicios</a>
            </li>
            <li class="nav-item {% if request.path == '/store/' %} active {% endif %} px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'core:store' %}">Visítanos</a>
            </li>
            <li class="nav-item {% if request.path == '/contact/' %} active {% endif %} px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'contact:contact' %}">Contacto</a>
            </li>
            <li class="nav-item {% if request.path|slice:":6" == '/blog/' %} active {% endif %} px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'blog:blog' %}">Blog</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>


    {% block content %}

    {% endblock %}

    <!-- Pié de página -->
    <footer class="footer text-faded text-center py-5">
      <div class="container">

        <p class="m-0">
        <!-- taggs de procesadores de contexto enviado desde processors.py -->
            {% if LINK_TWITTER %}
                <a href="{{ LINK_TWITTER }}" class="link">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
            {% endif %}
            {% if LINK_FACEBOOK  %}
                <a href="{{ LINK_FACEBOOK }}" class="link">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
            {% endif %}
            {% if LINK_INSTAGRAM %}
                <a href="{{ LINK_INSTAGRAM }}" class="link">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
            {% endif %}
	    </p>
        <p class="m-0 mbt">
        	<!--<a href="../../../pages/templates/pages/sample.html" class="link">Política de privacidad</a> ·
        	<a href="../../../pages/templates/pages/sample.html" class="link">Aviso legal</a> ·
        	<a href="../../../pages/templates/pages/sample.html" class="link">Cookies</a>-->
            <!-- se carga con load los template tags personalizados -->
            {% load pages_extras %}
            {% get_page_list as page_list %}
            {% for page in page_list %}
                <a href="{% url 'page:page' page.id page.title|slugify %}" class="link">{{ page.title }}</a>{% if not forloop.last  %} | {% endif %}
            {% endfor %}


		</p>
        <p class="m-0 mbt1">&copy; La Caffettiera 2018</p>
      </div>
	</footer>

    <!-- Bootstrap -->
    <script src="{% static 'core/vendor/jquery/jquery.min.js'%}"></script>
    <script src="{% static 'core/vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>

  </body>

</html>

core/templates/core/store.html
{% extends 'core/layout.html' %}

{% load static %}

{% block title %}Visítanos{% endblock %}

{% block content %}
<section class="page-section cta">
  <div class="container">
    <div class="row">
      <div class="col-xl-9 mx-auto">
        <div class="cta-inner text-center rounded">
          <h2 class="section-heading mb-5">
            <span class="section-heading-upper">Te esperamos</span>
            <span class="section-heading-lower">Visítanos</span>
          </h2>
          <ul class="list-unstyled list-hours mb-5 text-left mx-auto">
            <li class="list-unstyled-item list-hours-item d-flex">
              Lunes a viernes
              <span class="ml-auto">7:00 a 20:00</span>
            </li>
            <li class="list-unstyled-item list-hours-item d-flex">
              Sábados
              <span class="ml-auto">9:00 a 17:00</span>
            </li>
            <li class="list-unstyled-item list-hours-item d-flex">
              Domingos
              <span class="ml-auto">Cerrado</span>
            </li>
          </ul>
          <p class="address mb-5">
            <em>
              <strong>Avd. Infusiones nº 127</strong>
              <br>
              Barcelona
            </em>
          </p>
          <p class="mb-0">
            <small>
              <em>Llámanos y pregunta</em>
            </small>
            <br>
            (317) 585-8468
          </p>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

pages/templates/pages/sample.html
{% extends 'core/layout.html' %}


{% load static %}

{% block title %}{{ page.title }}{% endblock %}

{% block content %}
<section class="page-section about-heading">
  <div class="container">
    <div class="about-heading-content mbtm">
      <div class="row">
        <div class="col-xl-9 col-lg-10 mx-auto">
          <div class="bg-faded rounded p-5 forced">
            <h2 class="section-heading mb-4">
              <span class="section-heading-lower">{{ page.title }}</span>
            </h2>
            <div class="section-content">
                <p>{{ page.content|safe }}</p>
                {% if user.is_authenticated %}
                    <!-- edicion direca, haciendo referencia a la url del admin, ejemplo 'admin:App_Model_accion'_-->
                    <p><a href="{% url 'admin:pages_page_change' page.id %}">Editar</a></p>
                {% endif %}

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

services/templates/services/services.html
{% extends 'core/layout.html' %}


{% load static %}

{% block title %}Servicios{% endblock %}

{% block content %}
    {% for service in services %}
        <section class="page-section">
          <div class="container">
            <div class="product-item">
              <div class="product-item-title d-flex">
                <div class="bg-faded p-5 d-flex mr-auto rounded">
                  <h2 class="section-heading mb-0">
                    <span class="section-heading-upper">{{ service.subtitle }}</span>
                    <span class="section-heading-lower">{{ service.title }}</span>
                  </h2>
                </div>
              </div>
              <img class="product-item-img mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="{{ service.image.url }}" alt="">
              <div class="product-item-description d-flex ml-auto">
                <div class="bg-faded p-5 rounded">
                  <p class="mb-0">{{ service.content }}</p>
                </div>
              </div>
            </div>
          </div>
        </section>
    {% endfor %}

{% endblock %}